from .contracts import MethodParameter, MethodSpec


TOOLBOX_METHODS = [
    MethodSpec(
        id="source.project_part_images",
        name="Project Part Image Source",
        category="Input",
        description="Provides all images assigned to loaded inspection parts in the current VISTA project.",
        input_types=["any"],
        output_types=["image"],
        parameters=[
            MethodParameter(name="example_image_id", label="Choose Example", type="string", default=""),
        ],
        tags=["vista", "input", "parts"],
        jipipe_origin="Data source node",
    ),
    MethodSpec(
        id="output.versioned_image_artifact",
        name="Versioned Image Output",
        category="Output",
        description="Writes analysis output as a new VISTA image version or sidecar artifact while preserving the source image.",
        input_types=["image", "mask", "labels", "detections", "measurements", "metadata"],
        output_types=["metadata"],
        parameters=[
            MethodParameter(
                name="mode",
                label="Output Mode",
                type="select",
                default="versioned_image",
                options=["versioned_image", "overlay_metadata", "measurements_table", "review_only"],
            ),
            MethodParameter(
                name="version_strategy",
                label="Version Strategy",
                type="select",
                default="append_vn",
                options=["append_vn", "metadata_only"],
            ),
            MethodParameter(name="preserve_original", label="Preserve Original", type="boolean", default=True),
            MethodParameter(name="overlay_metadata", label="Write Overlay Metadata", type="boolean", default=True),
            MethodParameter(name="measurement_table", label="Write Measurements Table", type="boolean", default=True),
        ],
        tags=["vista", "output", "versioning", "metadata"],
        jipipe_origin="Data sink node",
    ),
    MethodSpec(
        id="preprocess.window_level_normalization",
        name="Window / Level Normalization",
        category="Preprocessing",
        description="Maps image intensities into a display or processing window using configurable level and width.",
        output_types=["image"],
        parameters=[
            MethodParameter(name="window", label="Window", type="float", default=400.0, min_value=1.0),
            MethodParameter(name="level", label="Level", type="float", default=40.0),
            MethodParameter(name="clip", label="Clip Outliers", type="boolean", default=True),
        ],
        tags=["normalization", "intensity", "window-level"],
        jipipe_origin="ImageJ contrast/intensity adjustment",
    ),
    MethodSpec(
        id="preprocess.minmax_normalization",
        name="Min-Max Normalization",
        category="Preprocessing",
        description="Rescales image intensities to a target numeric range.",
        output_types=["image"],
        parameters=[
            MethodParameter(name="output_min", label="Output Min", type="float", default=0.0),
            MethodParameter(name="output_max", label="Output Max", type="float", default=1.0),
        ],
        tags=["normalization", "intensity"],
        jipipe_origin="ImageJ normalize operation",
    ),
    MethodSpec(
        id="filter.gaussian_blur",
        name="Gaussian Blur",
        category="Filtering",
        description="Smooths image noise using a Gaussian kernel before segmentation or measurement.",
        output_types=["image"],
        parameters=[
            MethodParameter(name="sigma", label="Sigma", type="float", default=1.2, min_value=0.0, max_value=25.0),
        ],
        tags=["filter", "denoise"],
        jipipe_origin="Gaussian blur filter",
    ),
    MethodSpec(
        id="filter.median",
        name="Median Filter",
        category="Filtering",
        description="Reduces salt-and-pepper noise while preserving edges.",
        output_types=["image"],
        parameters=[
            MethodParameter(name="radius", label="Radius", type="integer", default=2, min_value=1, max_value=25),
        ],
        tags=["filter", "denoise"],
        jipipe_origin="Median filter",
    ),
    MethodSpec(
        id="threshold.otsu",
        name="Otsu Threshold",
        category="Segmentation",
        description="Creates a binary mask using automatic Otsu threshold selection.",
        output_types=["mask"],
        tags=["threshold", "segmentation"],
        jipipe_origin="Auto threshold",
    ),
    MethodSpec(
        id="threshold.manual",
        name="Manual Threshold",
        category="Segmentation",
        description="Creates a binary mask from a user supplied threshold.",
        output_types=["mask"],
        parameters=[
            MethodParameter(name="threshold", label="Threshold", type="float", default=0.5),
            MethodParameter(name="invert", label="Invert Mask", type="boolean", default=False),
        ],
        tags=["threshold", "segmentation"],
        jipipe_origin="Manual threshold",
    ),
    MethodSpec(
        id="segmentation.connected_components",
        name="Connected Components",
        category="Segmentation",
        description="Labels connected foreground regions in a binary mask.",
        input_types=["mask"],
        output_types=["labels", "measurements"],
        parameters=[
            MethodParameter(name="min_area_px", label="Min Area (px)", type="integer", default=12, min_value=0),
        ],
        tags=["labels", "particles", "segmentation"],
        jipipe_origin="Analyze particles / connected components",
    ),
    MethodSpec(
        id="segmentation.watershed_seeds",
        name="Watershed From Seeds",
        category="Segmentation",
        description="Splits touching regions using seeded watershed-style expansion.",
        input_types=["image", "mask"],
        output_types=["labels"],
        parameters=[
            MethodParameter(name="seed_spacing_px", label="Seed Spacing (px)", type="integer", default=18, min_value=1),
            MethodParameter(name="compactness", label="Compactness", type="float", default=0.01, min_value=0.0),
        ],
        tags=["watershed", "segmentation"],
        jipipe_origin="Watershed segmentation",
    ),
    MethodSpec(
        id="edge.canny",
        name="Canny Edges",
        category="Feature Detection",
        description="Detects edges using low and high hysteresis thresholds.",
        output_types=["mask"],
        parameters=[
            MethodParameter(name="low_threshold", label="Low Threshold", type="float", default=0.1),
            MethodParameter(name="high_threshold", label="High Threshold", type="float", default=0.3),
        ],
        tags=["edges", "features"],
        jipipe_origin="Edge detection",
    ),
    MethodSpec(
        id="morphology.open",
        name="Morphological Open",
        category="Morphology",
        description="Removes small foreground islands with erosion followed by dilation.",
        input_types=["mask"],
        output_types=["mask"],
        parameters=[
            MethodParameter(name="radius", label="Radius", type="integer", default=2, min_value=1),
        ],
        tags=["morphology", "cleanup"],
        jipipe_origin="Binary morphology",
    ),
    MethodSpec(
        id="morphology.close",
        name="Morphological Close",
        category="Morphology",
        description="Fills small gaps with dilation followed by erosion.",
        input_types=["mask"],
        output_types=["mask"],
        parameters=[
            MethodParameter(name="radius", label="Radius", type="integer", default=2, min_value=1),
        ],
        tags=["morphology", "cleanup"],
        jipipe_origin="Binary morphology",
    ),
    MethodSpec(
        id="measure.region_properties",
        name="Region Properties",
        category="Measurement",
        description="Computes area, centroid, bounding box, and intensity summaries for labeled regions.",
        input_types=["labels"],
        output_types=["measurements", "table"],
        parameters=[
            MethodParameter(
                name="features",
                label="Features",
                type="string",
                default="area,centroid,bbox,mean_intensity",
            ),
        ],
        tags=["measurement", "table"],
        jipipe_origin="Measure objects",
    ),
    MethodSpec(
        id="ml.yolov8.detect",
        name="YOLOv8 Object Detection",
        category="Machine Learning",
        description="Runs a YOLOv8 detector and emits bounding-box detections. The test toolbox exposes the contract; runtime model execution can be bound later.",
        output_types=["detections", "measurements"],
        parameters=[
            MethodParameter(name="model", label="Model", type="string", default="yolov8n.pt", required=True),
            MethodParameter(name="confidence", label="Confidence", type="float", default=0.25, min_value=0.0, max_value=1.0),
            MethodParameter(name="iou", label="IoU", type="float", default=0.45, min_value=0.0, max_value=1.0),
        ],
        tags=["yolov8", "detection", "ml"],
        jipipe_origin="External command / deep learning node",
    ),
    MethodSpec(
        id="ml.yolov8.segment",
        name="YOLOv8 Instance Segmentation",
        category="Machine Learning",
        description="Runs a YOLOv8 segmentation model and emits instance masks plus detections.",
        output_types=["mask", "detections", "measurements"],
        parameters=[
            MethodParameter(name="model", label="Model", type="string", default="yolov8n-seg.pt", required=True),
            MethodParameter(name="confidence", label="Confidence", type="float", default=0.25, min_value=0.0, max_value=1.0),
        ],
        tags=["yolov8", "segmentation", "ml"],
        jipipe_origin="External command / deep learning node",
    ),
]
