from .contracts import MethodParameter, MethodSpec


TOOLBOX_METHODS = [
    MethodSpec(
        id="source.project_part_images",
        name="Project Part Image Source",
        category="Input",
        description="Provides all images assigned to loaded inspection parts in the current VISTA project.",
        input_types=["any"],
        output_types=["image"],
        parameters=[
            MethodParameter(name="example_image_id", label="Choose Example", type="string", default=""),
        ],
        tags=["vista", "input", "parts"],
        jipipe_origin="Data source node",
    ),
    MethodSpec(
        id="output.versioned_image_artifact",
        name="Recipe / Artifact Output",
        category="Output",
        description="Stores processing versions as reproducible recipes, writes detections as metadata, persists spatial outputs as overlays, and materializes images only when needed.",
        input_types=["image", "mask", "labels", "detections", "measurements", "metadata"],
        output_types=["metadata"],
        parameters=[
            MethodParameter(
                name="mode",
                label="Output Mode",
                type="select",
                default="processing_sequence",
                options=["processing_sequence", "metadata_only", "overlay_artifact", "materialized_image", "review_only"],
            ),
            MethodParameter(
                name="export_policy",
                label="Export Policy",
                type="select",
                default="materialize_on_export",
                options=["materialize_on_export", "recipe_plus_artifacts", "metadata_only"],
            ),
            MethodParameter(name="materialize_processed_images", label="Materialize Processed Images", type="boolean", default=False),
        ],
        tags=["vista", "output", "recipe", "overlay", "metadata", "cache"],
        jipipe_origin="Data sink node",
    ),
    MethodSpec(
        id="preprocess.window_level_normalization",
        name="Window / Level Normalization",
        category="Preprocessing",
        description="Maps image intensities into a display or processing window using configurable level and width.",
        output_types=["image"],
        parameters=[
            MethodParameter(name="window", label="Window", type="float", default=400.0, min_value=1.0),
            MethodParameter(name="level", label="Level", type="float", default=40.0),
            MethodParameter(name="clip", label="Clip Outliers", type="boolean", default=True),
        ],
        tags=["normalization", "intensity", "window-level"],
        jipipe_origin="ImageJ contrast/intensity adjustment",
    ),
    MethodSpec(
        id="preprocess.minmax_normalization",
        name="Min-Max Normalization",
        category="Preprocessing",
        description="Rescales image intensities to a target numeric range.",
        output_types=["image"],
        parameters=[
            MethodParameter(name="output_min", label="Output Min", type="float", default=0.0),
            MethodParameter(name="output_max", label="Output Max", type="float", default=1.0),
        ],
        tags=["normalization", "intensity"],
        jipipe_origin="ImageJ normalize operation",
    ),
    MethodSpec(
        id="threshold.otsu",
        name="Otsu Threshold",
        category="Segmentation",
        description="Creates a binary mask using automatic Otsu threshold selection.",
        output_types=["mask"],
        tags=["threshold", "segmentation"],
        jipipe_origin="Auto threshold",
    ),
    MethodSpec(
        id="threshold.manual",
        name="Manual Threshold",
        category="Segmentation",
        description="Creates a binary mask from a user supplied threshold.",
        output_types=["mask"],
        parameters=[
            MethodParameter(name="threshold", label="Threshold", type="float", default=0.5),
            MethodParameter(name="invert", label="Invert Mask", type="boolean", default=False),
        ],
        tags=["threshold", "segmentation"],
        jipipe_origin="Manual threshold",
    ),
    MethodSpec(
        id="segmentation.connected_components",
        name="Connected Components",
        category="Segmentation",
        description="Labels connected foreground regions in a binary mask.",
        input_types=["mask"],
        output_types=["labels", "measurements"],
        parameters=[
            MethodParameter(name="min_area_px", label="Min Area (px)", type="integer", default=12, min_value=0),
        ],
        tags=["labels", "particles", "segmentation"],
        jipipe_origin="Analyze particles / connected components",
    ),
    MethodSpec(
        id="segmentation.watershed_seeds",
        name="Watershed From Seeds",
        category="Segmentation",
        description="Splits touching regions using seeded watershed-style expansion.",
        input_types=["image", "mask"],
        output_types=["labels"],
        parameters=[
            MethodParameter(name="seed_spacing_px", label="Seed Spacing (px)", type="integer", default=18, min_value=1),
            MethodParameter(name="compactness", label="Compactness", type="float", default=0.01, min_value=0.0),
        ],
        tags=["watershed", "segmentation"],
        jipipe_origin="Watershed segmentation",
    ),
    MethodSpec(
        id="edge.canny",
        name="Canny Edges",
        category="Feature Detection",
        description="Detects edges using low and high hysteresis thresholds.",
        output_types=["mask"],
        parameters=[
            MethodParameter(name="low_threshold", label="Low Threshold", type="float", default=0.1),
            MethodParameter(name="high_threshold", label="High Threshold", type="float", default=0.3),
        ],
        tags=["edges", "features"],
        jipipe_origin="Edge detection",
    ),
    MethodSpec(
        id="anomaly.asphalt_defects_heatmap",
        name="Asphalt Defects Heatmap",
        category="Anomaly Detection",
        description="Detects likely cracks and potholes in asphalt-like images and emits a red heatmap mask for overlay visualization.",
        output_types=["mask", "metadata"],
        parameters=[
            MethodParameter(name="sensitivity", label="Sensitivity", type="float", default=0.5, min_value=0.0, max_value=1.0),
            MethodParameter(name="blur_radius", label="Blur Radius", type="integer", default=2, min_value=0),
        ],
        tags=["anomaly", "asphalt", "cracks", "potholes", "heatmap"],
        jipipe_origin="Custom anomaly detector",
    ),
    MethodSpec(
        id="measure.region_properties",
        name="Region Properties",
        category="Measurement",
        description="Computes area, centroid, bounding box, and intensity summaries for labeled regions.",
        input_types=["labels"],
        output_types=["measurements", "table"],
        parameters=[
            MethodParameter(
                name="features",
                label="Features",
                type="string",
                default="area,centroid,bbox,mean_intensity",
            ),
        ],
        tags=["measurement", "table"],
        jipipe_origin="Measure objects",
    ),
    MethodSpec(
        id="ml.yolov8.detect",
        name="YOLOv8 Object Detection",
        category="Machine Learning",
        description="Runs a YOLOv8 detector and emits bounding-box detections. The test toolbox exposes the contract; runtime model execution can be bound later.",
        output_types=["detections", "measurements"],
        parameters=[
            MethodParameter(name="model", label="Model", type="string", default="yolov8n.pt", required=True),
            MethodParameter(name="confidence", label="Confidence", type="float", default=0.25, min_value=0.0, max_value=1.0),
            MethodParameter(name="iou", label="IoU", type="float", default=0.45, min_value=0.0, max_value=1.0),
        ],
        tags=["yolov8", "detection", "ml"],
        jipipe_origin="External command / deep learning node",
    ),
    MethodSpec(
        id="ml.yolov8.segment",
        name="YOLOv8 Instance Segmentation",
        category="Machine Learning",
        description="Runs a YOLOv8 segmentation model and emits instance masks plus detections.",
        output_types=["mask", "detections", "measurements"],
        parameters=[
            MethodParameter(name="model", label="Model", type="string", default="yolov8n-seg.pt", required=True),
            MethodParameter(name="confidence", label="Confidence", type="float", default=0.25, min_value=0.0, max_value=1.0),
        ],
        tags=["yolov8", "segmentation", "ml"],
        jipipe_origin="External command / deep learning node",
    ),
]
